### ISSUE TITLE
Fetch previous QC data point.

### ISSUE THREAD

**Issue by nicmostert** [HorizonsRC/hydrobot#44] opened 2024-02-06 21:36 UTC
If a date range is pulled, and the first available datapoint in standard data does not align with the first QC data point, we need to go further back in time to fetch the QC data before the first standard data point so that we can know the current QC score for the first data point. 

Bug shows up in the splitter logic somewhere.

**Comment by nicmostert** [comment] 2024-04-02 01:24
I can't remember why this was marked invalid... this seems like something we want?

**Comment by Sirvine1994** [comment] 2024-10-15 03:39
Functional duplicate of #42

**Closed by Sirvine1994** 2024-10-15 03:39 UTC
Labels: bug, invalid
